volumes:
  mongo_data:

services:
  # order-service:
  #   container_name: order-service
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '${APP_PORT}:8000'
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - DB_HOST=${DB_HOST}
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_NAME=${DB_NAME}
  #   depends_on:
  #     - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - mongo_data:/data/db
